### ISSUE TITLE
Create documentation for linux

### ISSUE THREAD

**Issue by m273d15** [swp-fu-eid/eid-fu-swp#17]

**Comment by m273d15** [comment]
Added in wiki: https://github.com/swp-fu-eid/eid-fu-swp/wiki/Setup-Testenvironment-on-Linux

**Comment by nils-wisiol** [comment]
@m273d15 , why not use `172.16` as IP4 prefix? 

A better way to create cryptographically sound keys would be `cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1`, instead of the `date` stanza. It also avoids to sleep for a second.

Could you update the repositories README to include a hint for setup docs in the wiki?

Other than that, I propose to close this.

**Comment by m273d15** [comment]
I thought that `172.16` does not work on all environments, but i will try it and ask the team members.

**Comment by m273d15** [comment]
I had time to try 172.16, but this led to the error `ERROR: for www  Cannot start service www: Invalid address 172.16.0.128: It does not belong to any of this network's subnets` during the execution of `docker-compose up`

**Comment by m273d15** [comment]
Ok, it was a layer 8 problem. After cleaning my whole setup and recreating the networks, 172.16 works for me!

**Comment by m273d15** [comment]
Added information that 172.16 should be used by default and the other way only in the case that the default value does not work
