### ISSUE TITLE
Summarize eCard-Framework

### ISSUE THREAD

**Issue by m273d15** [swp-fu-eid/eid-fu-swp#6]
https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Publikationen/TechnischeRichtlinien/TR03112/TR-03112-api_teil1.pdf

**Comment by auvin** [comment]
The eCard-API-Framework establishs uniform communication between the applications and the various chipcards. There are different chipcards because the eCard-strategy is not only used for the eID, but also for an electronic health card, passport etc.

The eCard-API-Framework is divided into four layers:
### Application-Layer
The Application-Layer contains various applications which use the Framework to access the eCards and their associated functions. But their intefaces are __not__ within the scope of this API.

### Identity-Layer
This Layer covers two interfaces for the use and management of electronic identities as well as for management of the eCard-API-Framework.
  * [eCard-Interface](https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Publikationen/TechnischeRichtlinien/TR03112/TR-03112-api_teil2.pdf?__blob=publicationFile&v=1): This interface encapsulates the main functions of the eCard-API-Framework in an application-orientated manner. For this purpose the eCard-Interface provides the following groups:
    * Functions for identity management
    * Signature functions
    * Encryption functions
  * [Management-Interface](https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Publikationen/TechnischeRichtlinien/TR03112/TR-03112-api_teil3.pdf?__blob=publicationFile&v=1): provides functions for updating the framework and the management of trusted identities, smart cards, card terminals, and default behaviour.

### Service-Access-Layer
The Service-Access-Layer provides functions for cryptographic primitives and biometric mechanisms in connection with cryptographic tokens.
  * [ISO24727-3-Interface](https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Publikationen/TechnischeRichtlinien/TR03112/TR-03112-api_teil4.pdf?__blob=publicationFile&v=1): This interface is a webservice-based implementation of the standard and contains functions to establish connections to smart cards and read or write data:
    * Card-Application Service Access
    * Connection Service
    * Card Application Service
    * Named data service
    * Cryptographic service
    * Authorization service
  * [Support-Interface](https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Publikationen/TechnischeRichtlinien/TR03112/TR-03112-api_teil5.pdf?__blob=publicationFile&v=1): Contains a range of supporting functions.

### Terminal-Layer
This layer contains the [IFD-Interface](https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Publikationen/TechnischeRichtlinien/TR03112/TR-03112-api_teil6.pdf?__blob=publicationFile&v=1) which takes over the generralisation of specific card terminal types and various interfaces.

**Comment by auvin** [comment]
I assume that we don't really need this API, because we will just communicate with the AusweisApp2 or similar applications, which will take over the direct communication with the eID-card.
If i am wrong, i think the [ISO24727-3-Interface](https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Publikationen/TechnischeRichtlinien/TR03112/TR-03112-api_teil4.pdf?__blob=publicationFile&v=1) provides all necessary services to connect to the card, perform cryptographic operations and read or write data.

**Comment by janles** [comment]
I read this document, too and I have the same opinion like @nielsgroth. I don't think we will need this API. The direct connection or/and communication is provided by the cardreader and the AusweisApp2 and we don't have to change or manipulate this.

I added @nielsgroth's first comment to our wiki.
